services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    networks:
      - kjaehyeok21_network
    restart: always

  spring-server:
    image: kjaehyeok21/profile_website:latest #FOR PRODUCTION
    # build:  # FOR DEVELOPMENT (INSTANT STARTUP)
    #   context: ./profile-website
    #   dockerfile: Dockerfile 
    ports:
      - 8080:8080
    networks:
      - kjaehyeok21_network
    depends_on:
      - redis
      - mysql
    volumes:
      - ${AWS_DIRECTORY}:/root/.aws
    restart: always

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    networks:
      - kjaehyeok21_network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
    volumes:
      - ${AWS_DIRECTORY}:/root/.aws

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - kjaehyeok21_network
    restart: always
    depends_on:
      - spring-server

volumes:
  jenkins_home:

networks:
  kjaehyeok21_network: