services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    networks:
      - mynetwork
    restart: always

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    environment:
      REDIS_ARGS: "--requirepass password --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ~* allcommands --user default off nopass nocommands"
    ports:
      - 6379:6379
    networks:
      - mynetwork
    restart: always

  spring-server:
    image: kjaehyeok21/profile_website
    ports:
      - 8081:8080
    networks:
      - mynetwork
    depends_on:
      - redis
      - mysql
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials
    restart: always

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    networks:
      - mynetwork
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB_NAME}

volumes:
  jenkins_home:

networks:
  mynetwork: