services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    networks:
      - mynetwork

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6380:6379
    networks:
      - mynetwork

  spring-server:
    build:
      context: ./profile-website
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    networks:
      - mynetwork
    depends_on:
      - redis
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials

volumes:
  jenkins_home:

networks:
  mynetwork: