services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    networks:
      - mynetwork
    restart: always

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6380:6379
    networks:
      - mynetwork
    restart: always

  spring-server:
    image: kjaehyeok21/profile_website
    ports:
      - 8081:8080
    networks:
      - mynetwork
    depends_on:
      - redis
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials
    restart: always

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    networks:
      - mynetwork
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  jenkins_home:

networks:
  mynetwork: