version: '3'
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - mynetwork

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6380:6379
    networks:
      - mynetwork

  spring-server:
    build:
      context: ./spring-server
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    networks:
      - mynetwork
    depends_on:
      - redis

volumes:
  jenkins_home:

networks:
  mynetwork: