  services:
    jenkins:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8080:8080
      volumes:
        - ./jenkins_home:/var/jenkins_home
        - "/usr/bin/docker:/usr/bin/docker"
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/usr/libexec/docker/cli-plugins/docker-compose:/usr/libexec/docker/cli-plugins/docker-compose"
        - "/usr/local/aws-cli:/usr/local/aws-cli"
        - type: bind
          source: $HOME/.aws
          target: /root/.aws
      user: root
      restart: always