services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    volumes:
      - "/usr/bin/docker:/usr/bin/docker"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/libexec/docker/cli-plugins/docker-compose:/usr/libexec/docker/cli-plugins/docker-compose"
      - "/usr/local/aws-cli:/usr/local/aws-cli"
      - "./jenkins_home:/var/jenkins_home"
      - "$HOME/.aws:/root/.aws"
    user: root
    restart: always
    environment:
      - AWS_DIRECTORY=${HOME}/.aws