pipeline {
    agent any
    
    stages {
        stage('Clone repository') {
            steps {
                git branch: 'main', url: 'https://github.com/zzawook/profile_website_backend.git'
            }
        }
        
        stage('Build and run Docker Compose') {
            steps {
                dir('profile_website_backend') {
                    sh './terminate_application.sh'
                    sh './run_application.sh'
                }
            }
        }

        stage("Finish") {
            steps {
                sh 'sudo docker images -qf dangling=true | xargs -I{} sudo docker rmi -f {}'
                sh 'sudo docker system prune -af'
            }
        }
    }
}