pipeline {
    agent any
    
    stages {
        stage('Clone repository') {
            steps {
                git branch: 'main', url: 'https://github.com/zzawook/profile_website_backend.git'
            }
        }
        
        stage('Build and run Docker Compose') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
}