pipeline {
    agent any
    stages {
        stage('Clone repository') {
            steps {
                // Git clone must be in profile_website_backend directory so that docker compose can find the running application with prefix "profile_website_backend" and terminate/resume with consistent name
                dir('profile_website_backend') { 
                    git branch: 'main', url: 'https://github.com/zzawook/profile_website_backend.git'
                }
            }
        }
        
        stage('Terminate docker compose') {
            steps {
                dir('profile_website_backend') {
                    sh './jenkins_restart_application.sh'
                }
            }
        }

        stage("Finish") {
            steps {
                sh 'docker images -qf dangling=true | xargs -I{} docker rmi -f {}'
                sh 'docker system prune -af'
            }
        }
    }
}