name: Docker-Jenkins CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image for Profile Website
        uses: docker/build-push-action@v2
        with:
          context: profile-website
          file: ./profile-website/Dockerfile
          push: true
          tags: kjaehyeok21/profile_website:latest

      - name: Trigger jenkins job
        uses: joshlk/jenkins-githubaction@master
        with:
          url: http://13.250.4.92:8080
          job_name: profile_website
          username: ${{ secrets.JENKINS_USER }}
          api_token: ${{ secrets.JENKINS_TOKEN }}
          timeout: "1000"